"""fix missing revision

Revision ID: 2d891300d088
Revises: 022f16464d6f
Create Date: 2025-06-12 13:57:06.664820

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2d891300d088"
down_revision: Union[str, None] = "022f16464d6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "items",
        sa.PrimaryKeyConstraint("id"),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("remaked_description", sa.String(), nullable=False),
        sa.UniqueConstraint("item"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("items")
    # ### end Alembic commands ###
